apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-consul-sync
  namespace: flux-system
spec:
  schedule: "*/2 * * * *"  # sync every 2 mins
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: alpine:3.19
            command: ["/bin/sh", "-c"]
            args:
              - |
                apk add --no-cache curl bash git
                # Clone our Git Repo for storing config files as config center
                git clone https://github.com/Rurutia1027/hands-on-shared-config-repo.git /tmp/config-repo
                # traverse all YAML files under subpath of
                for f in /tmp/config-repo/Hands-on-Lab.FluxCD-Consul-SpringBoot/spring-consul-app/*.yaml; do
                  APP=$(basename $f .yaml)
                  echo "🔄 Syncing $APP config to Consul"
                  curl --request PUT --data-binary @${f} http://consul-consul-server.consul:8500/v1/kv/config/$APP/data
                done
          restartPolicy: OnFailure