apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-consul-sync
  namespace: flux-system
spec:
  schedule: "*/2 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: alpine:3.19
            command: ["/bin/sh", "-c"]
            args:
              - |
                apk add --no-cache curl bash git
                git clone https://github.com/Rurutia1027/hands-on-shared-config-repo.git /tmp/config-repo
                FILE="/tmp/config-repo/Hands-on-Lab.FluxCD-Consul-SpringBoot/spring-consul-app/application.yaml"
                curl --request PUT --data-binary @"${FILE}" http://consul-consul-server.consul:8500/v1/kv/config/spring-consul-config-app/application-prod.yml
          restartPolicy: OnFailure