apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: your-dockerhub/demo-app:latest
        ports:
        - containerPort: 8180
        env:
        - name: SPRING_APPLICATION_NAME
          value: demo-app
        - name: SPRING_CLOUD_CONSUL_HOST
          value: consul-consul-server.consul
        - name: SPRING_CLOUD_CONSUL_PORT
          value: "8500"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: NodePort
  selector:
    app: demo-app
  ports:
  - port: 8180
    targetPort: 8180
    nodePort: 30080