spring:
  config:
    import: "optional:consul:"
  application:
    name: spring-consul-config-app
  cloud:
    consul:
      # in dev mode, declare the environment variable in the IDEA/Edit Configuration
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      config:
        watch:
          enabled: true
          delay: 500 # MS
        format: yaml
        prefix:
          - config/spring-consul-config-app
        data-key: application.yml
  profiles:
    active: prod

server:
  port: 8180

custom:
  config:
    featureA: true
    featureB: "Hello, Hands-on Lab!"
    maxItems: 10
    message: "Welcome to Flux + Consul integration demo!"

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info