name: Hands-on Lab Spring Boot Build & Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: spring-boot-app
        run: mvn clean package -Pbuild-and-push-docker-image -DskipTests

      - name: Generate Build Number
        id: build-number
        run: |
          BUILD_NUMBER=$(date '+%Y%m%d%H%M%S')
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Spring Boot Docker Image
        working-directory: spring-boot-app
        run: |
          mvn compile jib:build -Pbuild-and-push-docker-image -Dapp.image.tag=${{ env.BUILD_NUMBER }}